# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.
type: "php:7.0"

dependencies:
    php:
        wp-cli/wp-cli: "^1.1"
        psy/psysh: "^0.8.4"

# Configuration of the build of the application.
build:
    flavor: none

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "mysqldb:mysql"

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
    "/web/wp-content/uploads": "shared:files/uploads"
    "/web/wp-content/cache": "shared:files/cache"

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            # The public directory of the app, relative to its root.
            root: "web"
            # The front-controller script to send non-static requests to.
            passthru: "/index.php"
            # Wordpress has multiple roots (wp-admin) so the following is required
            index:
                - "index.php"
            # The number of seconds whitelisted (static) content should be cached.
            expires: 600
            scripts: true
            allow: true

hooks:
    build: |
        set -e
        cp .platform/wp-config/wp-config-platformsh.php web
        cp .platform/wp-config/wp-config.php web
